version: "3.9"

services:
  # =========================================================================
  # TẤT CẢ SERVICE ĐỀU ĐÃ ĐƯỢC TÍCH HỢP IAST
  # =========================================================================

  frontend:
    image: kienngo22022002/frontend:iast
    pull_policy: always # Nên để always nếu bạn chạy trên máy chủ khác để nó tự pull từ Docker Hub về
    container_name: frontend
    restart: always
    ports:
      - "8095:8080"
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8080
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - AD_SERVICE_ADDR=adservice:9555
      - SHOPPING_ASSISTANT_SERVICE_ADDR=shopping-assistant:8080
      - SEEKER_SERVER_URL=http://192.168.12.190:8082
      - SEEKER_PROJECT_KEY=microservices-demo-go

  paymentservice:
    image: kienngo22022002/paymentservice:iast
    pull_policy: always
    container_name: paymentservice
    restart: always
    environment:
      - PORT=50051
      - SEEKER_SERVER_URL=http://192.168.12.190:8082
      - SEEKER_PROJECT_KEY=microservices-demo-nodejs
      - SEEKER_AGENT_NAME=paymentservice-node-agent
      - SEEKER_GRPC_SUPPORT=true
      - SEEKER_JS_GRPC_SUPPORT=true
      # Đã thêm lại NODE_OPTIONS đúng chuẩn cho Node 20
      - NODE_OPTIONS=--import @seeker/agent/index.mjs
      - DISABLE_PROFILER=1
      - DISABLE_DEBUGGER=1
      - SEEKER_AGENT_LOG_LEVEL=DEBUG
      - NODE_TLS_REJECT_UNAUTHORIZED=0

  adservice:
    image: kienngo22022002/adservice:iast
    pull_policy: always
    container_name: adservice
    restart: always
    environment:
      - PORT=9555
      - SEEKER_SERVER_URL=http://192.168.12.190:8082
      - SEEKER_PROJECT_KEY=microservices-demo-java
      - JAVA_TOOL_OPTIONS=-javaagent:/app/seeker-agent.jar

  cartservice:
    image: kienngo22022002/cartservice:iast
    pull_policy: always
    container_name: cartservice
    restart: always
    environment:
      - REDIS_ADDR=redis-cart:6379
      - SEEKER_SERVER_URL=http://192.168.12.190:8082
      - SEEKER_PROJECT_KEY=microservices-demo-dotnet

  redis-cart:
    image: redis:alpine
    pull_policy: always
    container_name: redis-cart
    restart: always

  currencyservice:
    image: kienngo22022002/currencyservice:iast
    pull_policy: always
    container_name: currencyservice
    restart: always
    environment:
      - PORT=7000
      - DISABLE_PROFILER=1
      - NODE_OPTIONS=--import @seeker/agent/index.mjs
      - SEEKER_SERVER_URL=http://192.168.12.190:8082
      - SEEKER_PROJECT_KEY=microservices-demo-nodejs
      - SEEKER_AGENT_NAME=currencyservice-node-agent

  productcatalogservice:
    image: kienngo22022002/productcatalogservice:iast
    pull_policy: always
    container_name: productcatalogservice
    restart: always
    environment:
      - PORT=3550
      - SEEKER_SERVER_URL=http://192.168.12.190:8082
      - SEEKER_PROJECT_KEY=microservices-demo-go

  recommendationservice:
    image: kienngo22022002/recommendationservice:iast
    pull_policy: always
    container_name: recommendationservice
    restart: always
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SEEKER_SERVER_URL=http://192.168.12.190:8082
      - SEEKER_PROJECT_KEY=microservices-demo-python

  shippingservice:
    image: kienngo22022002/shippingservice:iast
    pull_policy: always
    container_name: shippingservice
    restart: always
    environment:
      - PORT=50051
      - SEEKER_SERVER_URL=http://192.168.12.190:8082
      - SEEKER_PROJECT_KEY=microservices-demo-go

  checkoutservice:
    image: kienngo22022002/checkoutservice:iast
    pull_policy: always
    container_name: checkoutservice
    restart: always
    environment:
      - PORT=5050
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
      - EMAIL_SERVICE_ADDR=emailservice:8080
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - SEEKER_SERVER_URL=http://192.168.12.190:8082
      - SEEKER_PROJECT_KEY=microservices-demo-checkout
      - SEEKER_GRPC_CLIENT_STREAM_ENABLED=true
      - SEEKER_GRPC_UNARY_CLIENT_ENABLED=true
      - SEEKER_AGENT_LOG_LEVEL=DEBUG

  emailservice:
    image: kienngo22022002/emailservice:iast
    pull_policy: always
    container_name: emailservice
    restart: always
    environment:
      - PORT=8080
      - SEEKER_SERVER_URL=http://192.168.12.190:8082
      - SEEKER_PROJECT_KEY=microservices-demo-python

  shopping-assistant:
    image: kienngo22022002/shoppingassistantservice:iast
    pull_policy: always
    container_name: shopping-assistant
    restart: always
    environment:
      - PORT=8080
      - SEEKER_SERVER_URL=http://192.168.12.190:8082
      - SEEKER_PROJECT_KEY=microservices-demo-python
  loadgenerator:
    image: kienngo22022002/loadgenerator:iast
    pull_policy: always
    container_name: loadgenerator
    restart: always
    environment:
      - FRONTEND_ADDR=frontend:8080
      - USERS=10
      - RATE=1
      - SEEKER_SERVER_URL=http://192.168.12.190:8082
      - SEEKER_PROJECT_KEY=microservices-demo-python
    depends_on:
      - frontend
